### PR TITLE
Made a new setting for templates to be an object

### LINKED ISSUE #16: Can't merge user and workspace settings
I have some user templates and I am setting up some project related templates. But since the `templates` setting is an array, I can't use the global user templates in that project.

From vscode [docs](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence):

> Values with primitive types and Array type are overridden but those with Object type are merged

I would propose adding a new templates setting to be an object with template `id` as key which should take preference over the current existing setting.

I am willing to make a PR if you agree.

### PR DESCRIPTION
**Pull request by pksunkara**
Closes #16

Tested and working perfectly

### CODE REVIEW

**Comment by asbjornh** [comment]
Nice!

I think I prefer something like this for the config schema though

```
      "properties": {
        "module-templates.templates": {
          "oneOf": [
            {
              "type": "array",
              "deprecationMessage": "Using an array for templates is deprecated and support will be removed in a future version. Use an object instead (see the documentation)",
              ... <the rest of the config options>
            },
            {
              "type": "object",
              "properties": {},
              "additionalProperties": {
                "type": "object",
                ... <the rest of the config options>
              }
            }
          ]
        },

**Comment by pksunkara** [comment]
Done. And tested the deprecation message too.

**Comment by asbjornh** [comment]
Thank you! I'm considering removing the detailed config schema for the templates array, but I'll look at that after merging

**Comment by asbjornh** [comment]
1.4 is now published to the marketplace. Thank you for your contribution! :)

**Pull request merged**
