### PR TITLE
Make sure `open` doesn't open a preview

### PR DESCRIPTION
**Pull request by pksunkara**
Currently, only the last file is being opened.

Btw, I have explored and tried all the templating extensions on the whole VS Code marketplace and I can confidently say that this is the best one.

### CODE REVIEW

**Comment by asbjornh** [comment]
Hi and thanks for the PR!

Could you describe the problem a bit more? I use the extension very frequently myself and I haven't noticed any issues with files opening after creation

**Comment by pksunkara** [comment]
If I have a folder template that creates multiple files with `open: true`, only one or them is being opened because all of them are opened as preview which means they override each other.

You probably have disabled the default editor preview setting in vscode.

**Comment by asbjornh** [comment]
Indeed I have!

I guess it makes sense for the `open` setting to override the configured preview behavior in this case.

**Comment by asbjornh** [comment]
It might be a while before I get this out. I need to find some time to sort out some Marketplace stuff

**Comment by pksunkara** [comment]
No problem as long as the PR is merged.

**Pull request merged**
