### PR TITLE
Skip creating files depending on questions, fixes #27

### LINKED ISSUE #27: Create files depending on questions
I have a template for which I want to ask a question whether they want a test file to be created or not. But I don't see a way to take the answer from the question and then not creating that file.

Would be happy to contribute a PR, but WDYT?

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Comment by pksunkara** [comment]
@asbjornh Do you have time to look into this? I would be willing to maintain this extension if you do not.

**Comment by asbjornh** [comment]
Hello! Thanks for offering to maintain this, but I’m a bit wary of giving write access to strangers.

As for these changes it’s not clear to me what they solve. Seems like this change will have the plugin silently fail in some cases which doesn’t seem good

**Comment by pksunkara** [comment]
> As for these changes it’s not clear to me what they solve. 

We improved the templating system to skip creating certain files based on the question/answers.

`extend` does not work as mentioned in #27 because:

> Because if there are two optional files, the `extend` would need us to create 4 templates

The changes in the PR are: If the filename resolves to an empty string, we skip creating that file. That way, users can do `name: {{{if test}}}test.ts{{{/if}}}` and have a `Create test?` question. If they answer yes, the `name` resolves to `test.ts`, and the file is created. if they answer no, the `name` resolves to `''`, and the file is not created.

---

 > Seems like this change will have the plugin silently fail in some cases which doesn’t seem good

Can you please expand on those cases? I am willing to fix the issues.

**Comment by pksunkara** [comment]
> but I’m a bit wary of giving write access to strangers.

Also, I am a big contributor to famous open-source projects if you check my github profile. Hope that helps alleviate some suspicion.

**Comment by asbjornh** [comment]
Thank you for explaining.

> extend does not work

I’m sure you can appreciate that this is a matter of opinion. In my opinion extend does exactly what I intended it to do (bar any actual bugs that I might be unaware of)

I’m well aware that you want it to do something else. I made this plugin for myself however, and to me it has been feature complete for quite a while now. To be frank it’s going to take a lot to get me to bother spending any time on this.

> Also, I am a big contributor to famous open-source projects if you check my github profile. Hope that helps alleviate some suspicion.

It does not. In case there’s confusion here, it’s not going to happen. Giving away write and publish access to strangers, regardless of how legitimate they may seem, is a highly irresponsible thing to do.

**Comment by pksunkara** [comment]
Just to make sure there's no miscommunication, I didn't mean that extend feature has bugs. 

What I meant is that extend feature does not support this use case because it becomes increasingly complex as we want to add more options to templates.

---

If you are saying that you don't intend to add this feature at all, that's fine with me, feel free to close this PR.

**Comment by asbjornh** [comment]
> If you are saying that you don't intend to add this feature at all, that's fine with me, feel free to close this PR.

Sorry for being unclear. I don’t intend to add this feature!

**Pull request closed without merging**
